export interface Database {
  public: {
    Tables: {
      alerts: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          keywords: string;
          cities: string[];
          category: string;
          min_price: number | null;
          max_price: number | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          last_check_at: string | null;
          error_count: number;
          last_error: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          keywords: string;
          cities: string[];
          category: string;
          min_price?: number | null;
          max_price?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          last_check_at?: string | null;
          error_count?: number;
          last_error?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          keywords?: string;
          cities?: string[];
          category?: string;
          min_price?: number | null;
          max_price?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          last_check_at?: string | null;
          error_count?: number;
          last_error?: string | null;
        };
      };
      matches: {
        Row: {
          id: string;
          alert_id: string;
          craigslist_id: string;
          url: string;
          title: string;
          datetime: string;
          location: string;
          category: string;
          price: string | null;
          longitude: string | null;
          latitude: string | null;
          map_accuracy: string | null;
          post_content: string | null;
          notices: string[] | null;
          phone_numbers: string[] | null;
          pics: string[] | null;
          amenities: string[] | null;
          available_from: string | null;
          manufacturer: string | null;
          condition: string | null;
          model: string | null;
          attributes: string[] | null;
          compensation: string | null;
          employment_type: string | null;
          job_title: string | null;
          education: string | null;
          dates: string | null;
          created_at: string;
          updated_at: string;
          viewed_at: string | null;
        };
        Insert: {
          id?: string;
          alert_id: string;
          craigslist_id: string;
          url: string;
          title: string;
          datetime: string;
          location: string;
          category: string;
          price?: string | null;
          longitude?: string | null;
          latitude?: string | null;
          map_accuracy?: string | null;
          post_content?: string | null;
          notices?: string[] | null;
          phone_numbers?: string[] | null;
          pics?: string[] | null;
          amenities?: string[] | null;
          available_from?: string | null;
          manufacturer?: string | null;
          condition?: string | null;
          model?: string | null;
          attributes?: string[] | null;
          compensation?: string | null;
          employment_type?: string | null;
          job_title?: string | null;
          education?: string | null;
          dates?: string | null;
          created_at?: string;
          updated_at?: string;
          viewed_at?: string | null;
        };
        Update: {
          id?: string;
          alert_id?: string;
          craigslist_id?: string;
          url?: string;
          title?: string;
          datetime?: string;
          location?: string;
          category?: string;
          price?: string | null;
          longitude?: string | null;
          latitude?: string | null;
          map_accuracy?: string | null;
          post_content?: string | null;
          notices?: string[] | null;
          phone_numbers?: string[] | null;
          pics?: string[] | null;
          amenities?: string[] | null;
          available_from?: string | null;
          manufacturer?: string | null;
          condition?: string | null;
          model?: string | null;
          attributes?: string[] | null;
          compensation?: string | null;
          employment_type?: string | null;
          job_title?: string | null;
          education?: string | null;
          dates?: string | null;
          created_at?: string;
          updated_at?: string;
          viewed_at?: string | null;
        };
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          created_at: string;
          updated_at: string;
          subscription_tier: string;
          subscription_status: string;
          subscription_end_date: string | null;
          alert_limit: number;
          city_limit: number;
          email_notifications: boolean;
          email_frequency: string;
        };
        Insert: {
          id: string;
          email: string;
          created_at?: string;
          updated_at?: string;
          subscription_tier?: string;
          subscription_status?: string;
          subscription_end_date?: string | null;
          alert_limit?: number;
          city_limit?: number;
          email_notifications?: boolean;
          email_frequency?: string;
        };
        Update: {
          id?: string;
          email?: string;
          created_at?: string;
          updated_at?: string;
          subscription_tier?: string;
          subscription_status?: string;
          subscription_end_date?: string | null;
          alert_limit?: number;
          city_limit?: number;
          email_notifications?: boolean;
          email_frequency?: string;
        };
      };
    };
  };
}
